/-
Copyright (c) 2026 NoneMore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: NoneMore
-/
import MorleyCategoricityTheorem.ModelTheory.LanguageEmbedding
import MorleyCategoricityTheorem.ModelTheory.PartialEmbedding
import MorleyCategoricityTheorem.ModelTheory.Syntax
import MorleyCategoricityTheorem.ModelTheory.Types

/-!
# Transporting complete types along language equivalences

A language equivalence `e : L ≃ᴸ L'` that carries a theory `T` onto a theory `T'` identifies the
spaces of complete types over `T` and over `T'`.  A complete type over `T` with variables `α` is,
by definition, a maximal `L[[α]]`-theory extending the constants expansion of `T`, so the transport
acts on sentences of `L[[α]]` through the language equivalence `e.addConstants α`, which extends `e`
to the constant expansions while leaving the free-variable constants unchanged.

The Stone topology on complete types is generated by the basic clopen sets `T.typesWith φ`, and the
transport carries the basic open set of a sentence to the basic open set of the renamed sentence.
Consequently it is a homeomorphism, and specialising to the parameter-language equivalence of a
partial elementary embedding `f : A ↪ₚₑ[L] B` yields a homeomorphism between the type spaces over
`A` and over `B`.

## Main definitions

- `FirstOrder.Language.Theory.CompleteType.completeTypeEquiv`: the equivalence of complete types
  `T.CompleteType α ≃ T'.CompleteType α` induced by a language equivalence `e : L ≃ᴸ L'` and a proof
  that `e.toLHom.onTheory T = T'`.
- `FirstOrder.Language.Theory.CompleteType.completeTypeHomeomorph`: the same transport, bundled as a
  homeomorphism of Stone spaces.
- `FirstOrder.Language.PartialElementaryEmbedding.completeTypeOverHomeomorph`: the homeomorphism of
  complete type spaces over the parameter sets of a partial elementary embedding.

## Main results

- `FirstOrder.Language.Theory.CompleteType.mem_completeTypeEquiv_iff`: membership in the
  transported complete type is membership of the renamed sentence in the original type.
- `FirstOrder.Language.Theory.CompleteType.mem_completeTypeEquiv_symm_iff`: the inverse membership
  rule, formulated for the inverse equivalence.
- `FirstOrder.Language.Theory.CompleteType.image_typesWith` and
  `FirstOrder.Language.Theory.CompleteType.preimage_typesWith`: the transport carries basic open
  sets to basic open sets, in image and preimage form.
- `FirstOrder.Language.Theory.CompleteType.continuous_completeTypeEquiv` and its `_symm` variant:
  the transport and its inverse are continuous with respect to the Stone topology.
- `FirstOrder.Language.Theory.CompleteType.mem_completeTypeHomeomorph_iff`: membership rule for the
  bundled homeomorphism, available without unfolding the maximal theories.
- `FirstOrder.Language.PartialElementaryEmbedding.mem_completeTypeOverHomeomorph_iff` and its
  `_symm` variant: the forward and inverse membership rules for the parameter-set homeomorphism.
- `FirstOrder.Language.PartialElementaryEmbedding.completeTypeOverHomeomorph_image_typesWith`: the
  parameter-set homeomorphism carries basic open sets over `A` to basic open sets over `B`.
- `FirstOrder.Language.LEquiv.isMaximal_onTheory`: a language equivalence carries maximal theories
  to maximal theories.

The syntax-only functoriality laws used here (`LHom.onTheory_comp`, `LHom.id_onTheory`,
`LHom.onSentence_not`, the mutual-inverse laws for `LEquiv`, and
`LEquiv.onTheory_addConstants_lhomWithConstants`) live in `ModelTheory/Syntax.lean`, while
`LEquiv.toLHom_addConstants_comp_lhomWithConstants` lives in `ModelTheory/LanguageEmbedding.lean`.
-/

universe u v u' v' w w' x

namespace FirstOrder

namespace Language

namespace LEquiv

variable {L : Language.{u, v}} {L' : Language.{u', v'}}

/-- A language equivalence carries maximal theories to maximal theories.

Satisfiability transfers along the equivalence, and each sentence of the image is the image of a
sentence of the source theory or of its negation. -/
theorem isMaximal_onTheory (e : L ≃ᴸ L') (T : L.Theory) (hT : T.IsMaximal) :
    (e.toLHom.onTheory T).IsMaximal := by
  refine ⟨(Theory.isSatisfiable_onTheory_iff (LEmbedding.ofLEquiv e).injective).mpr hT.1, ?_⟩
  intro φ
  obtain ⟨ψ, rfl⟩ := e.onSentence.surjective φ
  rcases hT.mem_or_not_mem ψ with hψ | hψ
  · exact Or.inl (LHom.mem_onTheory.mpr ⟨ψ, hψ, rfl⟩)
  · exact Or.inr (LHom.mem_onTheory.mpr ⟨ψ.not, hψ, LHom.onSentence_not e.toLHom ψ⟩)

end LEquiv

namespace Theory

namespace CompleteType

variable {L : Language.{u, v}} {L' : Language.{u', v'}}
variable {T : L.Theory} {T' : L'.Theory} {α : Type w}

/-- The inverse language equivalence carries the transported theory back: if `e` identifies `T` with
`T'`, then `e.symm` identifies `T'` with `T`. -/
private theorem onTheory_symm (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T') :
    e.symm.toLHom.onTheory T' = T := by
  simpa [← h] using LEquiv.invLHom_onTheory_toLHom_onTheory e T

/-- The forward transport of a complete type along a language equivalence `e` identifying `T` with
`T'`: it renames the symbols of the underlying maximal theory along the constants-extended
equivalence `e.addConstants α`. -/
private noncomputable def map (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T')
    (p : T.CompleteType α) : T'.CompleteType α where
  toTheory := (e.addConstants α).toLHom.onTheory p.toTheory
  subset' := by
    rw [← h, ← LEquiv.onTheory_addConstants_lhomWithConstants]
    exact Set.image_mono p.subset
  isMaximal' := LEquiv.isMaximal_onTheory (e.addConstants α) p.toTheory p.isMaximal

/-- Applying the inverse transport after the forward transport returns the original theory. -/
private theorem map_map_toTheory (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T')
    (p : T.CompleteType α) :
    (map e.symm (onTheory_symm e h) (map e h p)).toTheory = p.toTheory :=
  LEquiv.invLHom_onTheory_toLHom_onTheory (e.addConstants α) p.toTheory

/-- Applying the forward transport after the inverse transport returns the original theory. -/
private theorem map_map_toTheory' (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T')
    (p : T'.CompleteType α) :
    (map e h (map e.symm (onTheory_symm e h) p)).toTheory = p.toTheory :=
  LEquiv.toLHom_onTheory_invLHom_onTheory (e.addConstants α) p.toTheory

/-- A language equivalence that carries a theory `T` onto a theory `T'` induces an equivalence
between the complete types over `T` and the complete types over `T'` with the same variables.

The forward direction renames the symbols of the underlying maximal theory along `e.addConstants α`,
and the inverse direction renames them back along `(e.symm).addConstants α`. -/
noncomputable def completeTypeEquiv (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T') :
    T.CompleteType α ≃ T'.CompleteType α where
  toFun := map e h
  invFun := map e.symm (onTheory_symm e h)
  left_inv := fun p => ext (map_map_toTheory e h p)
  right_inv := fun p => ext (map_map_toTheory' e h p)

/-- Membership in the transported complete type: a sentence belongs to the image of `p` exactly
when its preimage under the constants-extended language equivalence belongs to `p`. -/
@[simp]
theorem mem_completeTypeEquiv_iff (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T')
    (p : T.CompleteType α) (φ : L'[[α]].Sentence) :
    φ ∈ completeTypeEquiv e h p ↔ (e.addConstants α).onSentence.symm φ ∈ p := by
  change φ ∈ (e.addConstants α).onSentence '' p.toTheory ↔
    (e.addConstants α).onSentence.symm φ ∈ p.toTheory
  exact Set.mem_image_equiv

/-- Membership in the inverse of the transported complete type: a sentence belongs to the preimage
of `p` exactly when its image under the constants-extended language equivalence belongs to `p`. -/
@[simp]
theorem mem_completeTypeEquiv_symm_iff (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T')
    (p : T'.CompleteType α) (φ : L[[α]].Sentence) :
    φ ∈ (completeTypeEquiv e h).symm p ↔ (e.addConstants α).onSentence φ ∈ p := by
  change φ ∈ ((e.addConstants α).onSentence).symm '' p.toTheory ↔
    (e.addConstants α).onSentence φ ∈ p.toTheory
  exact Set.mem_image_equiv

/-! ### Stone topology -/

/-- Pulling back a basic open set along the transport of complete types is the basic open set
defined by the inverse-renamed sentence. -/
@[simp]
theorem preimage_typesWith (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T')
    (σ : L'[[α]].Sentence) :
    completeTypeEquiv e h ⁻¹' T'.typesWith σ =
      T.typesWith ((e.addConstants α).onSentence.symm σ) :=
  Set.ext fun p => by simp only [Set.mem_preimage, mem_typesWith_iff, mem_completeTypeEquiv_iff]

/-- Pulling back a basic open set along the inverse transport of complete types is the basic open
set defined by the renamed sentence. -/
@[simp]
theorem preimage_typesWith_symm (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T')
    (φ : L[[α]].Sentence) :
    (completeTypeEquiv e h).symm ⁻¹' T.typesWith φ =
      T'.typesWith ((e.addConstants α).onSentence φ) := by
  ext p
  simp only [Set.mem_preimage, mem_typesWith_iff, mem_completeTypeEquiv_symm_iff]

/-- Transporting complete types along a language equivalence carries the basic open set defined by a
sentence to the basic open set defined by the renamed sentence.

This explicit basic-open transport rule is the downstream form used to move isolating formulas
between the two type spaces. -/
@[simp]
theorem image_typesWith (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T')
    (φ : L[[α]].Sentence) :
    completeTypeEquiv e h '' T.typesWith φ =
      T'.typesWith ((e.addConstants α).onSentence φ) := by
  rw [Equiv.image_eq_preimage_symm, preimage_typesWith_symm]

/-- Transporting complete types along a language equivalence is continuous for the Stone topology,
because every basic open set pulls back to a basic open set. -/
theorem continuous_completeTypeEquiv (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T') :
    Continuous (completeTypeEquiv (α := α) e h) := by
  refine (CompleteType.isTopologicalBasis_range_typesWith (T := T') (α := α)).continuous_iff.mpr ?_
  rintro s ⟨σ, rfl⟩
  simpa using CompleteType.isOpen_typesWith _

/-- The inverse of the transport of complete types is continuous for the Stone topology: as a
function it is the forward transport along the inverse language equivalence `e.symm`. -/
theorem continuous_completeTypeEquiv_symm (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T') :
    Continuous (completeTypeEquiv (α := α) e h).symm :=
  continuous_completeTypeEquiv (α := α) e.symm (onTheory_symm e h)

/-- The equivalence of complete types induced by a language equivalence that identifies the theory
`T` with the theory `T'` is a homeomorphism for the Stone topologies. -/
noncomputable def completeTypeHomeomorph (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T') :
    T.CompleteType α ≃ₜ T'.CompleteType α where
  toEquiv := completeTypeEquiv e h
  continuous_toFun := continuous_completeTypeEquiv e h
  continuous_invFun := continuous_completeTypeEquiv_symm e h

/-- The bundled homeomorphism acts on complete types as the unbundled transport equivalence. -/
@[simp]
theorem completeTypeHomeomorph_apply (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T')
    (p : T.CompleteType α) :
    completeTypeHomeomorph e h p = completeTypeEquiv e h p :=
  rfl

/-- Membership in the image of the bundled homeomorphism is membership of the inverse-renamed
sentence in the original complete type. -/
@[simp]
theorem mem_completeTypeHomeomorph_iff (e : L ≃ᴸ L') (h : e.toLHom.onTheory T = T')
    (p : T.CompleteType α) (σ : L'[[α]].Sentence) :
    σ ∈ completeTypeHomeomorph e h p ↔ (e.addConstants α).onSentence.symm σ ∈ p := by
  rw [completeTypeHomeomorph_apply, mem_completeTypeEquiv_iff]

end CompleteType

end Theory

namespace PartialElementaryEmbedding

variable {L : Language.{u, v}} {M : Type w} {N : Type w'}
variable [L.Structure M] [L.Structure N]
variable {A : Set M} {B : Set N}

/-- The homeomorphism between the spaces of complete types over the parameter sets of a partial
elementary embedding `f : A ↪ₚₑ[L] B`.

A partial elementary embedding identifies the parameter-expanded complete theories of `M` over `A`
and of `N` over `B`, so the generic transport of complete types along its parameter-language
equivalence is a homeomorphism of the corresponding Stone spaces. This expresses the blueprint
statement that `S_α^M(A)` and `S_α^N(B)` are homeomorphic. -/
noncomputable def completeTypeOverHomeomorph (f : A ↪ₚₑ[L] B) (α : Type x) :
    L.CompleteTypeOver A α ≃ₜ L.CompleteTypeOver B α :=
  Theory.CompleteType.completeTypeHomeomorph f.parameterLEquiv f.map_completeTheory

/-- The parameter-set homeomorphism acts on complete types as the transport of complete types along
the parameter-language equivalence. -/
@[simp]
theorem completeTypeOverHomeomorph_apply (f : A ↪ₚₑ[L] B) (α : Type x)
    (p : L.CompleteTypeOver A α) :
    f.completeTypeOverHomeomorph α p =
      Theory.CompleteType.completeTypeEquiv f.parameterLEquiv f.map_completeTheory p :=
  rfl

/-- Membership in the image of the parameter-set homeomorphism is membership of the inverse-renamed
sentence in the original complete type, available without unfolding maximal theories. -/
@[simp]
theorem mem_completeTypeOverHomeomorph_iff (f : A ↪ₚₑ[L] B) (α : Type x)
    (p : L.CompleteTypeOver A α) (σ : (L[[B]])[[α]].Sentence) :
    σ ∈ f.completeTypeOverHomeomorph α p ↔
      (f.parameterLEquiv.addConstants α).onSentence.symm σ ∈ p := by
  rw [completeTypeOverHomeomorph_apply, Theory.CompleteType.mem_completeTypeEquiv_iff]

/-- Membership in the preimage of the parameter-set homeomorphism is membership of the renamed
sentence in the complete type over `B`. -/
@[simp]
theorem mem_completeTypeOverHomeomorph_symm_iff (f : A ↪ₚₑ[L] B) (α : Type x)
    (p : L.CompleteTypeOver B α) (σ : (L[[A]])[[α]].Sentence) :
    σ ∈ (f.completeTypeOverHomeomorph α).symm p ↔
      (f.parameterLEquiv.addConstants α).onSentence σ ∈ p :=
  Theory.CompleteType.mem_completeTypeEquiv_symm_iff f.parameterLEquiv f.map_completeTheory p σ

/-- The parameter-set homeomorphism carries the basic open set defined by a sentence over `A` to
the basic open set defined by the renamed sentence over `B`. -/
theorem completeTypeOverHomeomorph_image_typesWith (f : A ↪ₚₑ[L] B) (α : Type x)
    (φ : (L[[A]])[[α]].Sentence) :
    f.completeTypeOverHomeomorph α '' (L[[A]].completeTheory M).typesWith φ =
      (L[[B]].completeTheory N).typesWith ((f.parameterLEquiv.addConstants α).onSentence φ) :=
  Theory.CompleteType.image_typesWith f.parameterLEquiv f.map_completeTheory φ

end PartialElementaryEmbedding

end Language

end FirstOrder
